Repository studiohyperdrive/hyperdrive-opensource, pull requests merged in 2023-08, with the labels that each got.

#47 fix(table): Add lodash to the peer dependencies and add documentation
  projects/table/README.md
  projects/table/package.json
Labels: bug

#45 feat(ngx-store): Export remaining needed interfaces and add ability to pass a selectId function - ngx-store
  projects/store/package-lock.json
  projects/store/package.json
  projects/store/src/lib/store/interfaces/index.ts
  projects/store/src/lib/store/interfaces/store-generator.ts
  projects/store/src/lib/store/utils/store-generator.util/store-generator.util.ts
  projects/store/src/public-api.ts
Labels: enhancement

#48 fix(i18n): Fix issue with missing language due to individual translation services
  angular.json
  projects/i18n-test/.eslintrc.json
  projects/i18n-test/src/app/app-routing.module.ts
  projects/i18n-test/src/app/app.component.html
  projects/i18n-test/src/app/app.component.scss
  projects/i18n-test/src/app/app.component.spec.ts
  projects/i18n-test/src/app/app.component.ts
  projects/i18n-test/src/app/app.module.ts
  projects/i18n-test/src/assets/.gitkeep
  projects/i18n-test/src/assets/feature/nl.json
  projects/i18n-test/src/assets/shared/nl.json
  projects/i18n-test/src/favicon.ico
  projects/i18n-test/src/feature/feature.module.ts
  projects/i18n-test/src/feature/feature.routing.module.ts
  projects/i18n-test/src/feature/pages/feature.component.ts
  projects/i18n-test/src/feature/translation.loader.ts
  projects/i18n-test/src/index.html
  projects/i18n-test/src/main.ts
  projects/i18n-test/src/styles.scss
  projects/i18n-test/tsconfig.app.json
  projects/i18n-test/tsconfig.spec.json
  projects/i18n/package.json
  projects/i18n/src/lib/services/i18n/i18n.service.spec.ts
  projects/i18n/src/lib/services/i18n/i18n.service.ts
  projects/i18n/src/lib/services/index.ts
  projects/i18n/src/lib/services/root-i18n/root-i18n.service.ts
Labels: bug

#49 fix(i18n): Fetch the current language from the root service in case it does not exist
  projects/i18n-test/src/assets/feature/nl.json
  projects/i18n-test/src/feature/pages/feature.component.ts
  projects/i18n/README.md
  projects/i18n/package.json
  projects/i18n/src/lib/services/i18n/i18n.service.ts
Labels: bug

#50 feat(ngx-table): Add radio-button-select to the ngx-table
  angular.json
  projects/table-test/.eslintrc.json
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.component.scss
  projects/table-test/src/app/app.component.spec.ts
  projects/table-test/src/app/app.component.ts
  projects/table-test/src/app/app.module.ts
  projects/table-test/src/assets/.gitkeep
  projects/table-test/src/favicon.ico
  projects/table-test/src/index.html
  projects/table-test/src/main.ts
  projects/table-test/src/styles.scss
  projects/table-test/tsconfig.app.json
  projects/table-test/tsconfig.spec.json
  projects/table/README.md
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.html
  projects/table/src/lib/table/ngx-table.component.ts
Labels: enhancement

#57 feat(table): Add root config to the table component
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.component.ts
  projects/table-test/src/app/app.module.ts
  projects/table/README.md
  projects/table/package.json
  projects/table/src/lib/index.ts
  projects/table/src/lib/table/ngx-table.component.html
  projects/table/src/lib/table/ngx-table.component.ts
  projects/table/src/lib/token/index.ts
  projects/table/src/lib/token/ngx-table-config.token.ts
Labels: enhancement

#58 fix(table): Mark the table row as selected if there's only one item and the showDetailRow is said to `on-single-item`
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.html
Labels: bug

#59 feat(utils): added withRouterLinksPipe to allow for in-text router-link conversion
  projects/i18n/README.md
  projects/utils/README.md
  projects/utils/package-lock.json
  projects/utils/package.json
  projects/utils/src/lib/pipes/index.ts
  projects/utils/src/lib/pipes/with-router-links/with-router-links.config.ts
  projects/utils/src/lib/pipes/with-router-links/with-router-links.md
  projects/utils/src/lib/pipes/with-router-links/with-router-links.pipe.spec.ts
  projects/utils/src/lib/pipes/with-router-links/with-router-links.pipe.ts
  projects/utils/src/lib/pipes/with-router-links/with-router-links.types.ts
  projects/utils/src/lib/utils.const.ts
  projects/utils/src/lib/utils.types.ts
Labels: ngx-utils

#60 fix(ngx-table): Don't show open row state if no detail row is provided
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.component.ts
  projects/table-test/src/app/app.module.ts
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.ts
Labels: bug

#61 fix(ngx-forms): Refactor custom update value and validity implementation and fix disable/enable state
  angular.json
  projects/form-test/.eslintrc.json
  projects/form-test/src/app/app.component.html
  projects/form-test/src/app/app.component.scss
  projects/form-test/src/app/app.component.ts
  projects/form-test/src/app/app.module.ts
  projects/form-test/src/assets/.gitkeep
  projects/form-test/src/favicon.ico
  projects/form-test/src/form-accessor/form-accessor.component.ts
  projects/form-test/src/index.html
  projects/form-test/src/main.ts
  projects/form-test/src/styles.scss
  projects/form-test/tsconfig.app.json
  projects/forms/README.md
  projects/forms/package.json
  projects/forms/src/lib/abstracts/data-form/data-form.accessor.ts
  projects/forms/src/lib/abstracts/form-accessor-container/form-accessor-container.ts
  projects/forms/src/lib/abstracts/form/form.accessor.ts
  projects/forms/src/lib/utils/custom-update-value-and-validity/custom-update-value-and-validity.util.spec.ts
  projects/forms/src/lib/utils/custom-update-value-and-validity/custom-update-value-and-validity.util.ts
  projects/forms/src/lib/utils/form-accessor/form-accessor.utils.ts
  projects/forms/src/public-api.ts
Labels: bug

#62 feat(ngx-table): Add ability to emit when the showDetail is set to `on-single-item`
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.component.ts
  projects/table-test/src/app/app.module.ts
  projects/table/README.md
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.ts
  projects/table/src/lib/token/ngx-table-config.token.ts
Labels: enhancement

#63 fix(table): Fix error in ngOnChanges
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.ts
Labels: bug

#64 Fix(selected-row): deselect selected row upon data change
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.component.scss
  projects/table-test/src/app/app.component.ts
  projects/table-test/src/app/app.module.ts
  projects/table-test/src/app/wrapper/wrapper.component.ts
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.ts
Labels: bug

#65 fix(ngx-table): Fix selected row state on data changes
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.ts
Labels: bug
