Repository studiohyperdrive/hyperdrive-opensource, pull requests merged in 2023-11, with the labels that each got.

#73 fix(table): Fix incorrect checkbox handling and incorrect writeValue handling
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.component.ts
  projects/table-test/src/app/app.module.ts
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.html
  projects/table/src/lib/table/ngx-table.component.ts
Labels: bug

#74 feat(table): Add ability to hide the header and fix the issue with the radio button
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.module.ts
  projects/table/README.md
  projects/table/package.json
  projects/table/src/lib/interfaces/index.ts
  projects/table/src/lib/interfaces/show-header-requirements.ts
  projects/table/src/lib/pipes/index.ts
  projects/table/src/lib/pipes/show-header/show-header.pipe.spec.ts
  projects/table/src/lib/pipes/show-header/show-header.pipe.ts
  projects/table/src/lib/table/ngx-table.component.html
  projects/table/src/lib/table/ngx-table.component.ts
  projects/table/src/lib/token/ngx-table-config.token.ts
Labels: bug, enhancement

#77 feat(log): add logpipe for debugging
  projects/utils/package.json
  projects/utils/src/lib/pipes/index.ts
  projects/utils/src/lib/pipes/log/log.pipe.md
  projects/utils/src/lib/pipes/log/log.pipe.ts
Labels: enhancement

#78 fix(table): Add prevent reset form on new data flow to table
  projects/table-test/src/app/app.component.html
  projects/table-test/src/app/app.component.ts
  projects/table/package.json
  projects/table/src/lib/table/ngx-table.component.html
  projects/table/src/lib/table/ngx-table.component.ts
  projects/table/src/lib/utils/generate-form.util.ts
  projects/table/src/lib/utils/handle-form-changes.util.ts
  projects/table/src/lib/utils/index.ts
  projects/table/src/lib/utils/reset-form.util.ts
Labels: enhancement

#79 fix(log): remove void expression from truthy check
  projects/utils/package.json
  projects/utils/src/lib/pipes/log/log.pipe.ts
Labels: bug, ngx-utils

#81 feat(angular): Upgrade packages to Angular 17
  angular.json
  package-lock.json
  package.json
  projects/forms/package.json
  projects/i18n/package.json
  projects/store-test/src/app/app.module.ts
  projects/store/package.json
  projects/table/package.json
  projects/utils/package.json
  tsconfig.json
Labels: ngx-forms, upgrade, ngx-table, ngx-store, ngx-utils

#82 fix(forms): Expose the onTouch functionality to the extenders
  projects/form-test/src/app/app.module.ts
  projects/form-test/src/date-input/date-input.component.html
  projects/form-test/src/date-input/date-input.component.ts
  projects/form-test/src/form-accessor/form-accessor.component.ts
  projects/forms/package.json
  projects/forms/src/lib/abstracts/data-form/data-form.accessor.ts
  projects/forms/src/lib/abstracts/form/form.accessor.ts
Labels: bug, ngx-forms
